import { useState } from 'react';
import { ArrowRight, Sparkles, ShieldCheck, Plane, ShoppingBag, Fuel, Utensils, ChevronDown, RotateCcw, CreditCard, Info, Check, TrendingUp } from 'lucide-react';

const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';
const demo = {monthly_income:70000,credit_score:760,age:28,annual_fee_max:1500,reward_preference:'cashback',spending:{shopping:15000,dining:8000,fuel:4000,travel:5000,grocery:6000,utilities:3000}};
type Rec = {id:string;name:string;issuer:string;annual_fee:number;score:number;confidence:number;estimated_annual_rewards:number;estimated_net_annual_value:number;reward_type:string;why:string[];limitations:string[];lounge_access:boolean};
export default function App(){
 const [profile,setProfile]=useState<any>(demo),[rows,setRows]=useState<Rec[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('Overview'),[travel,setTravel]=useState(5000),[simulation,setSimulation]=useState<any>(null),[comparison,setComparison]=useState<Rec[]>([]);
 async function recommend(p=profile){setBusy(true);setError('');try{const r=await fetch(API+'/api/recommend',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});if(!r.ok)throw new Error('Could not generate recommendations. Check that the CardLens API is running.');const d=await r.json();setRows(d.recommendations||[]);if(!d.recommendations?.length)setError(d.message||'No cards match this profile yet.')}catch(e:any){setError(e.message||'CardLens is temporarily unavailable. Your profile is still here.')}finally{setBusy(false)}}
 async function compareTop(){if(rows.length<2){setError('Generate recommendations first to compare eligible demo cards.');return}setBusy(true);setError('');try{const r=await fetch(API+'/api/compare',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({profile,card_ids:rows.slice(0,2).map(c=>c.id)})});if(!r.ok)throw new Error();setComparison((await r.json()).cards||[])}catch{setError('Comparison unavailable. Please retry.')}finally{setBusy(false)}}
 async function runSimulation(){setBusy(true);try{const r=await fetch(API+'/api/simulate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({profile,changes:{travel}})});if(!r.ok)throw new Error();setSimulation(await r.json())}catch{setError('Simulation unavailable. Please retry when the API is connected.')}finally{setBusy(false)}}
 const spend=(key:string,val:number)=>setProfile({...profile,spending:{...profile.spending,[key]:val}});
 const best=rows[0]; const topCategory=Object.entries(profile.spending as Record<string,number>).sort((a,b)=>b[1]-a[1])[0]?.[0]||'spending'; const icons:any={shopping:ShoppingBag,dining:Utensils,fuel:Fuel,travel:Plane,grocery:ShoppingBag,utilities:CreditCard};
 return <div className="shell"><aside className="sidebar"><a className="brand" href="#"><span className="brandmark"><CreditCard size={20}/></span><span>cardlens<span className="brand-ai"> AI</span></span></a><div className="nav-label">WORKSPACE</div>{['Overview','Your profile','Recommendations','Explore what if','Compare cards'].map((n,i)=><button key={n} onClick={()=>setTab(n)} className={'nav-item '+(tab===n?'active':'')}><span className="nav-icon">{['⌂','◉','✧','↗','⇄'][i]}</span>{n}{n==='Recommendations'&&rows.length>0&&<span className="nav-count">{rows.length}</span>}</button>)}<div className="sidebar-bottom"><div className="safe"><ShieldCheck size={16}/><span>Your data stays in this session</span></div><div className="user"><div className="avatar">P</div><div><b>Personal profile</b><small>Demo mode</small></div><ChevronDown size={15}/></div></div></aside>
 <main className="main"><header className="topbar"><div className="crumb">Workspace <span>/</span> {tab}</div><div className="top-actions"><span className="demo-pill"><i/> DEMO MODE</span><button className="iconbtn" title="Reset demo profile" onClick={()=>{setProfile(demo);setSimulation(null)}}><RotateCcw size={16}/></button><div className="avatar small">P</div></div></header>
 <div className="content"><section className="welcome"><div><div className="eyebrow"><Sparkles size={14}/> PERSONALIZED CARD MATCHING</div><h1>Find the card that<br/><em>fits your life.</em></h1><p>Tell us how you spend. We’ll help you understand which benefits could work harder for you.</p><button className="primary" onClick={()=>recommend()} disabled={busy}>{busy?'Finding your fit…':'See my recommendations'} <ArrowRight size={17}/></button><span className="trust"><ShieldCheck size={14}/> No card number or bank login needed</span></div><div className="hero-art"><div className="halo"/><div className="hero-card"><div className="hc-top"><span>cardlens</span><span className="chip"/></div><div className="hc-orb"/><div className="hc-bottom"><div><small>MADE FOR YOUR EVERYDAY</small><b>Everyday Cashback</b></div><span>VISA</span></div></div><div className="float-score"><span>YOUR CARDLENS SCORE</span><b>{best?.score ?? '—'}<small>{best?'/100':''}</small></b><div className="score-line"><i/></div><small>{best?'Model-generated fit':'Run a match to see score'}</small></div><div className="float-reward"><span className="reward-icon"><TrendingUp size={17}/></span><div><small>EST. NET ANNUAL VALUE</small><b>{best?'₹'+best.estimated_net_annual_value.toLocaleString('en-IN'):'—'}</b></div><span className="up">↗</span></div><div className="sparkle s1">✳</div><div className="sparkle s2">✦</div></div></section>

 {tab==='Your profile'&&<section className="panel profile-editor"><div className="eyebrow muted">YOUR CARDLENS PROFILE</div><h2>Tell us what fits</h2><p>Fields are optional. Values stay in this browser session.</p><div className="profile-fields"><label>Monthly income (₹)<input type="number" min="0" value={profile.monthly_income??''} onChange={e=>setProfile({...profile,monthly_income:e.target.value===''?null:+e.target.value})}/></label><label>Credit score <input type="number" min="300" max="900" value={profile.credit_score??''} onChange={e=>setProfile({...profile,credit_score:e.target.value===''?null:+e.target.value})}/></label><label>Maximum annual fee (₹)<input type="number" min="0" value={profile.annual_fee_max} onChange={e=>setProfile({...profile,annual_fee_max:+e.target.value})}/></label><label>Reward preference<select value={profile.reward_preference} onChange={e=>setProfile({...profile,reward_preference:e.target.value})}><option value="cashback">Cashback</option><option value="travel">Travel</option><option value="fuel">Fuel</option><option value="rewards">Flexible rewards</option></select></label></div><h3>Monthly spending</h3><div className="profile-fields spend-fields">{Object.entries(profile.spending).map(([key,value]:any)=><label key={key}>{key[0].toUpperCase()+key.slice(1)} (₹)<input type="number" min="0" value={value} onChange={e=>spend(key,Math.max(0,+e.target.value))}/></label>)}</div><button className="primary" onClick={()=>{setTab('Overview');recommend()}} disabled={busy}>Save profile & find matches <ArrowRight size={16}/></button></section>}


 {tab==='Compare cards'&&<section className="panel compare-panel"><div className="eyebrow muted">SMART CARD COMPARISON</div><h2>Compare your top matches</h2><p>Side-by-side estimated value based on your spending profile. Terms shown are demo data.</p><button className="primary" onClick={compareTop} disabled={busy||rows.length<2}>{busy?'Comparing…':'Compare my top two'} <ArrowRight size={16}/></button>{comparison.length>0&&<div className="compare-results">{comparison.map(c=><article key={c.id}><span className="live-tag">FOR YOUR PROFILE</span><h3>{c.name}</h3><div className="compare-value">₹{c.estimated_net_annual_value.toLocaleString('en-IN')}<small> est. net annual value</small></div><p>Rewards ₹{c.estimated_annual_rewards.toLocaleString('en-IN')} · Annual fee ₹{c.annual_fee}</p><p>Score {c.score}/100 · {c.reward_type} preference</p><small>Synthetic demo terms. Check the issuer for verified current details.</small></article>)}</div>}</section>}

 <div className="demo-banner"><div className="demo-stamp"><Info size={16}/></div><div><b>You’re exploring with sample data</b><span>Demo card benefits and reward rates are illustrative, not current issuer offers.</span></div><button onClick={()=>recommend()}>Generate demo match <ArrowRight size={15}/></button></div>
 <section className="section-head"><div><div className="eyebrow muted">YOUR MONEY, IN CONTEXT</div><h2>Your spending snapshot</h2><p>A quick view of the monthly spend you shared.</p></div><button className="text-btn" onClick={()=>setTab('Your profile')}>Edit profile <ArrowRight size={15}/></button></section>
 <div className="dashboard-grid"><div className="panel spend-panel"><div className="panel-title"><div><b>Monthly spending</b><span>₹{Object.values(profile.spending).reduce((a:any,b:any)=>a+b,0).toLocaleString('en-IN')} total</span></div><button className="dots">···</button></div><div className="spend-list">{Object.entries(profile.spending).map(([k,v]:any)=>{const Icon=icons[k]||CreditCard;const pct=Math.round(v/Math.max(1,Object.values(profile.spending).reduce((a:any,b:any)=>a+b,0))*100);return <div className="spend-row" key={k}><div className={'cat-icon '+k}><Icon size={16}/></div><span className="cat-name">{k[0].toUpperCase()+k.slice(1)}</span><div className="bar"><i style={{width:pct+'%'}}/></div><b>₹{v.toLocaleString('en-IN')}</b></div>})}</div><button className="edit-spend" onClick={()=>setTab('Your profile')}>＋ Adjust spending</button></div>
 <div className="panel insight-panel"><div className="insight-top"><span className="insight-icon"><Sparkles size={17}/></span><span className="live-tag"><i/> PROFILE INSIGHT</span></div><h3>Your top category is<br/>{topCategory}.</h3><p>This insight comes from the monthly spending amounts in your profile. Your preferred reward style is {profile.reward_preference}.</p><div className="insight-foot"><span><Check size={14}/> Based on your profile</span><span>↗</span></div><div className="insight-decor">✳</div></div></div>
 {error&&<div className="error"><Info size={16}/>{error}<button onClick={()=>recommend()}>Retry</button></div>}
 {rows.length>0&&<><section className="section-head rec-head"><div><div className="eyebrow muted">MATCHED TO YOUR SPENDING</div><h2>Your top recommendations</h2><p>Ranked by a deterministic model-generated suitability score.</p></div><span className="results-tag">{rows.length} DEMO MATCHES</span></section><div className="cards-grid">{rows.slice(0,3).map((c,i)=><article className={'rec-card '+(i===0?'winner':'')} key={c.id}><div className="rec-card-top"><span className={'card-mini '+c.reward_type}>{c.reward_type==='travel'?<Plane size={20}/>:c.reward_type==='fuel'?<Fuel size={20}/>:<CreditCard size={20}/>}</span><span className="rank">0{i+1}</span></div><div className="issuer">{c.issuer} · DEMO</div><h3>{c.name}</h3><div className="score-row"><span>CardLens score</span><b>{c.score}<small>/100</small></b></div><div className="value-row"><span>Est. net annual value</span><b>₹{c.estimated_net_annual_value.toLocaleString('en-IN')}</b></div><div className="value-row light"><span>Est. rewards · ₹{c.annual_fee} fee</span><span>₹{c.estimated_annual_rewards.toLocaleString('en-IN')}</span></div><div className="why"><b>Why this could fit</b>{c.why.map(x=><span key={x}><Check size={14}/>{x}</span>)}</div><div className="fineprint">{c.limitations[0]}</div><button className="outline" onClick={()=>setTab('Compare cards')}>Explore card <ArrowRight size={15}/></button></article>)}</div></>}
 <section className="whatif"><div className="wi-copy"><div className="eyebrow"><Sparkles size={14}/> SIGNATURE FEATURE</div><h2>What if your<br/><em>spending changed?</em></h2><p>Explore how a shift in your monthly habits could change your card matches.</p><div className="slider-title"><span><Plane size={16}/> Monthly travel spending</span><b>₹{travel.toLocaleString('en-IN')}</b></div><input type="range" min="0" max="40000" step="1000" value={travel} onChange={e=>setTravel(+e.target.value)}/><div className="range-label"><span>₹0</span><span>₹40,000</span></div><button className="primary" onClick={runSimulation} disabled={busy}>{busy?'Recalculating…':'Explore this scenario'} <ArrowRight size={16}/></button></div><div className="wi-result">{simulation?<><div className="result-label"><span className="live-tag"><i/> SIMULATION COMPLETE</span></div><h3>Here’s what changed</h3><p>Ranking recalculated using the same rules and your updated travel spend.</p><div className="rank-compare"><div><small>BEFORE</small><b>{simulation.before.recommendations[0]?.name||'No match'}</b><span>#{1}</span></div><div className="swap">→</div><div className="after"><small>AFTER</small><b>{simulation.after.recommendations[0]?.name||'No match'}</b><span>#{1}</span></div></div><div className="why-shift"><Sparkles size={15}/><span>{simulation.before.recommendations[0]?.id===simulation.after.recommendations[0]?.id?'Your top match stayed the same for this scenario.':'Your top match changed based on the updated spending profile.'}</span></div></>:<><div className="ranking-head"><span>YOUR CURRENT RANKING</span><span>MODEL-GENERATED FIT</span></div>{(rows.length?rows.slice(0,3):[{name:'Everyday Cashback (Demo)',reward_type:'cashback',score:92},{name:'Explorer Travel (Demo)',reward_type:'travel',score:85},{name:'Fuel & Dine (Demo)',reward_type:'fuel',score:78}] as any).map((c:any,i:number)=><div className="rank-item" key={c.name}><span className="rank-num">{i+1}</span><span className="rank-dot">{i===0?'✳':i===1?'✦':'◈'}</span><b>{c.name}</b><span className="rank-score">{c.score}<small>/100</small></span></div>)}<div className="recalc"><span className="recalc-icon"><TrendingUp size={17}/></span><span>Change your travel spend<br/><small>to see how the ranking responds</small></span><ArrowRight size={16}/></div></>}</div></section>
 <div className="disclaimer"><ShieldCheck size={16}/><p><b>A helpful starting point, not a promise.</b> This tool provides informational estimates based on the information you provide. Offers shown are demo data; actual approval, eligibility, rewards, and terms are determined by each card issuer.</p></div>
 <footer><a className="brand footer-brand" href="#"><span className="brandmark"><CreditCard size={16}/></span><span>cardlens<span className="brand-ai"> AI</span></span></a><span>See the card that’s right for you.</span><span>Made for more confident card decisions <span className="heart">✳</span></span></footer>
 </div></main></div>
}
