import { FormEvent, ReactNode, useEffect, useState } from 'react';

const API = import.meta.env.VITE_API_BASE_URL ?? (import.meta.env.DEV ? 'http://localhost:8000' : '');
type User = { id: string; name: string; email: string };
type Profile = { monthly_income:number|null; credit_score:number|null; annual_fee_max:number|null; reward_preference:string|null; spending:Record<string,number> };
const blankProfile = ():Profile => ({monthly_income:null,credit_score:null,annual_fee_max:null,reward_preference:null,spending:{shopping:0,dining:0,fuel:0,travel:0,grocery:0,utilities:0}});
const categories=['shopping','dining','fuel','travel','grocery','utilities'];
const messageOf=(data:any,fallback:string)=>typeof data?.detail==='string'?data.detail:data?.detail?.message||fallback;

export default function AuthGate({children}:{children:ReactNode}) {
 const [user,setUser]=useState<User|null>(null);
 const [screen,setScreen]=useState<'loading'|'public'|'login'|'signup'|'onboarding'|'ready'|'error'>('loading');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[showPassword,setShowPassword]=useState(false);
 const [profile,setProfile]=useState<Profile>(blankProfile()),[step,setStep]=useState(0);
 async function loadProfile(){const response=await fetch(API+'/api/profile');if(!response.ok)throw new Error('Could not load your profile. Please try again.');const data=await response.json();if(data.complete&&data.profile){setProfile({...blankProfile(),...data.profile,spending:{...blankProfile().spending,...data.profile.spending}});setScreen('ready')}else{setProfile(blankProfile());setStep(1);setScreen('onboarding')}}
 useEffect(()=>{let active=true;fetch(API+'/api/auth/me').then(async response=>{if(!active)return;if(response.status===401){setScreen('public');return}const data=await response.json();if(!response.ok)throw new Error(messageOf(data,'CardLens is temporarily unavailable.'));setUser(data.user);await loadProfile()}).catch(err=>{if(active){setError(err.message);setScreen('error')}});return()=>{active=false}},[]);
 async function authenticate(event:FormEvent){event.preventDefault();setError('');if(screen==='signup'&&password!==confirmPassword){setError('Passwords do not match.');return}if(screen==='signup'&&!/(?=.*[A-Za-z])(?=.*\d).{10,}/.test(password)){setError('Use at least 10 characters, including a letter and a number.');return}setBusy(true);try{const endpoint=screen==='signup'?'signup':'login';const response=await fetch(API+'/api/auth/'+endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(screen==='signup'?{name,email,password}:{email,password})});const data=await response.json();if(!response.ok)throw new Error(messageOf(data,'Unable to sign in. Please check your details.'));setUser(data.user);if(endpoint==='signup'){setProfile(blankProfile());setStep(1);setScreen('onboarding')}else await loadProfile()}catch(err:any){setError(err.message||'Unable to sign in. Please try again.')}finally{setBusy(false)}}
 async function persistProfile(){const response=await fetch(API+'/api/profile',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(profile)});const data=await response.json();if(!response.ok)throw new Error(messageOf(data,'Your profile could not be saved.'));return data}
 async function advance(){setError('');if(step<6){setStep(step+1);return}if(!Object.values(profile.spending).some(amount=>Number(amount)>0)){setError('Enter monthly spending in at least one category to get meaningful matches. Income and credit score can stay blank.');return}setBusy(true);try{await persistProfile();const response=await fetch(API+'/api/recommend',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(profile)});const data=await response.json();if(!response.ok)throw new Error(messageOf(data,'Recommendations could not be generated yet. Your profile is saved; please retry.'));setScreen('ready')}catch(err:any){setError(err.message||'Your profile could not be saved.')}finally{setBusy(false)}}
 async function logout(){setBusy(true);setError('');try{const response=await fetch(API+'/api/auth/logout',{method:'POST'});if(!response.ok)throw new Error('Could not sign out. Please retry.');setUser(null);setProfile(blankProfile());setStep(0);setPassword('');setConfirmPassword('');setScreen('public')}catch(err:any){setError(err.message||'Could not sign out. Please retry.')}finally{setBusy(false)}}
 const setSpend=(key:string,value:string)=>setProfile({...profile,spending:{...profile.spending,[key]:value===''?0:Math.max(0,Number(value))}});
 if(screen==='loading')return <div className="auth-loading" role="status">Opening your CardLens workspace…</div>;
 if(screen==='ready'&&user)return <div className="account-shell"><header className="account-bar"><a className="account-brand" href="#">cardlens <span>AI</span></a><div><span className="account-greeting">Welcome, {user.name}</span><button onClick={logout} disabled={busy} className="account-logout">{busy?'Signing out…':'Sign out'}</button></div></header>{children}</div>;
 if(screen==='error')return <main className="auth-screen"><section className="auth-card"><a className="account-brand" href="#">cardlens <span>AI</span></a><h1>Your workspace is unavailable</h1><p>{error}</p><button className="auth-submit" onClick={()=>{setError('');setScreen('login')}}>Try again</button></section></main>;
 if(screen==='public')return <main className="public-landing">
   <header className="landing-nav"><a className="account-brand" href="#">cardlens <span>AI</span></a><nav><a href="#how-it-works">How it works</a><a href="#features">Features</a><button className="landing-login" onClick={()=>{setError('');setScreen('login')}}>Log in</button></nav></header>
   <section className="landing-hero"><div className="landing-copy"><span className="auth-eyebrow">A CLEARER WAY TO CHOOSE</span><h1>Find the card<br/>that fits your life.</h1><p>CardLens AI understands how you spend, compares your options, and explains which cards fit you best.</p><div className="landing-actions"><button className="auth-submit" onClick={()=>setScreen('signup')}>Get my recommendations <span>→</span></button><a href="#how-it-works">Explore how it works</a></div><small>Private by design · No bank credentials or card numbers required</small></div>
    <div className="landing-visual"><div className="landing-glow"/><article className="landing-card"><div className="landing-card-top"><b>cardlens <i>AI</i></b><span>✳</span></div><div className="landing-chip"/><div className="landing-card-bottom"><span>YOUR SPENDING, UNDERSTOOD</span><b>•••• &nbsp; •••• &nbsp; ••••</b></div></article><div className="landing-metric score"><small>SAMPLE CARDLENS SCORE</small><b>86<span>/100</span></b><em>Illustrative profile</em></div><div className="landing-metric value"><small>SAMPLE ANNUAL VALUE</small><b>₹12,480</b><em>Illustrative estimate</em></div><div className="landing-metric match"><small>EXAMPLE SPENDING MATCH</small><b>Shopping · Dining</b><em>Example categories</em></div></div>
   </section>
   <section id="how-it-works" className="landing-how"><span className="auth-eyebrow">HOW IT WORKS</span><h2>A little context goes a long way.</h2><div className="landing-steps">{[['01','Tell us how you spend','Share a few optional details about your monthly habits.'],['02','CardLens analyzes your profile','A transparent, deterministic score compares the available cards.'],['03','Get personalized recommendations','See the match, estimated value, and trade-offs behind each result.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
   <section id="features" className="landing-features"><span className="auth-eyebrow">BUILT FOR CLARITY</span><h2>Useful guidance, with the reasoning in view.</h2><div>{['Personalized card matching','Transparent recommendations','What-If simulations','AI Advisor','Multilingual voice','Privacy-first design'].map((feature,i)=><article key={feature}><b>0{i+1}</b><span>{feature}</span></article>)}</div><p className="landing-data-note">Current card catalog contains illustrative data. Confirm current benefits and terms with each issuer.</p></section>
   <section className="landing-end"><h2>Make your next card choice<br/>with a clearer picture.</h2><button className="auth-submit" onClick={()=>setScreen('signup')}>Get my recommendations <span>→</span></button></section>
   <footer className="landing-footer"><a className="account-brand" href="#">cardlens <span>AI</span></a><span>No bank credentials or card numbers required.</span><button onClick={()=>setScreen('login')}>Log in</button></footer>
 </main>;
 if(screen==='onboarding')return <main className="auth-screen"><section className="auth-card onboarding-card">
  <div className="auth-brand-row"><a className="account-brand" href="#">cardlens <span>AI</span></a><span className="auth-security">PRIVATE PROFILE SETUP</span></div>
  <div className="auth-eyebrow">YOUR PROFILE · {String(step).padStart(2,'0')} / 06</div>
  <div className="onboarding-progress"><span style={{width:((step/6)*100)+'%'}}/></div>
  {step===1&&<><h1>Welcome to CardLens, {user?.name?.split(' ')[0]||'there'}.</h1><p>We’ll use your answers to estimate reward fit. You can skip income and credit score; enter at least one monthly spending category to get useful matches.</p><div className="onboarding-summary"><b>Your information stays yours.</b><span>No bank password, CVV, or card number needed. Your profile is saved when you finish setup.</span></div></>}
  {step===2&&<><h1>What’s your monthly income?</h1><p>This is optional and only helps estimate eligibility against illustrative criteria.</p><label>Monthly income (₹)<input type="number" min="0" max="100000000" value={profile.monthly_income??''} onChange={e=>setProfile({...profile,monthly_income:e.target.value===''?null:Number(e.target.value)})} placeholder="Skip if you prefer"/></label></>}
  {step===3&&<><h1>Where do you spend?</h1><p>Enter typical monthly amounts. These stay editable in your profile.</p><div className="onboarding-fields spend-onboarding">{categories.map(key=><label key={key}>{key[0].toUpperCase()+key.slice(1)} (₹)<input type="number" min="0" max="10000000" value={profile.spending[key]??0} onChange={e=>setSpend(key,e.target.value)}/></label>)}</div></>}
  {step===4&&<><h1>Credit score</h1><p>Optional. It helps estimate broad eligibility fit; it does not predict issuer approval.</p><label>Score<input type="number" min="300" max="900" value={profile.credit_score??''} onChange={e=>setProfile({...profile,credit_score:e.target.value===''?null:Number(e.target.value)})} placeholder="300–900, or skip"/></label></>}
  {step===5&&<><h1>What matters most?</h1><p>Choose a reward style and annual fee comfort level, or leave both unknown.</p><div className="onboarding-fields"><label>Reward preference<select value={profile.reward_preference??''} onChange={e=>setProfile({...profile,reward_preference:e.target.value||null})}><option value="">Not sure</option><option value="cashback">Cashback</option><option value="travel">Travel</option><option value="fuel">Fuel</option><option value="rewards">Flexible rewards</option></select></label><label>Annual fee limit (₹)<input type="number" min="0" max="1000000" value={profile.annual_fee_max??''} onChange={e=>setProfile({...profile,annual_fee_max:e.target.value===''?null:Number(e.target.value)})} placeholder="No limit"/></label></div></>}
  {step===6&&<><h1>Review your profile</h1><p>These details power your deterministic estimates. You can revise them any time.</p><div className="onboarding-review"><span>Monthly income <b>{profile.monthly_income==null?'Not shared':'₹'+profile.monthly_income.toLocaleString('en-IN')}</b></span><span>Credit score <b>{profile.credit_score??'Not shared'}</b></span><span>Reward preference <b>{profile.reward_preference??'Not set'}</b></span><span>Annual fee limit <b>{profile.annual_fee_max==null?'No limit':'₹'+profile.annual_fee_max.toLocaleString('en-IN')}</b></span><span>Monthly spend entered <b>{Object.values(profile.spending).filter(n=>n>0).length} of 6 categories</b></span></div></>}
  {error&&<p className="auth-error" role="alert">{error}</p>}
  <div className="onboarding-controls">{step>1&&<button className="auth-back" disabled={busy} onClick={()=>setStep(step-1)}>← Back</button>}<button className="auth-submit" disabled={busy} onClick={advance}>{busy?'Saving…':step===6?'Save and see recommendations':'Save and continue'}</button></div>
  {step===1&&<button type="button" className="auth-back" disabled={busy} onClick={()=>setStep(2)}>Start my profile →</button>}
  <button type="button" className="auth-back" disabled={busy} onClick={logout}>Sign out</button>
 </section></main>;
 const signup=screen==='signup';
 return <main className="auth-screen"><section className="auth-card"><div className="auth-brand-row"><a className="account-brand" href="#" onClick={e=>{e.preventDefault();setScreen('public')}}>cardlens <span>AI</span></a><span className="auth-security">Private by design</span></div><div className="auth-eyebrow">PERSONAL CREDIT CARD INSIGHTS</div><h1>{signup?'A smarter match starts here.':'Welcome back.'}</h1><p>{signup?'Create an account to keep your profile and recommendations with you.':'Sign in to continue to your personalized workspace.'}</p><form onSubmit={authenticate}>
 {signup&&<label>Your name<input required autoComplete="name" maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="Name"/></label>}
 <label>Email address<input required type="email" autoComplete="email" maxLength={320} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>
 <label>Password<span className="password-field"><input required type={showPassword?'text':'password'} autoComplete={signup?'new-password':'current-password'} minLength={signup?10:1} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} placeholder={signup?'At least 10 characters':'Your password'}/><button type="button" onClick={()=>setShowPassword(!showPassword)}>{showPassword?'Hide':'Show'}</button></span></label>
 {signup&&<><label>Confirm password<input required type={showPassword?'text':'password'} autoComplete="new-password" minLength={10} maxLength={128} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Enter your password again"/></label><small className="auth-hint">Use 10+ characters with at least one letter and one number.</small></>}
 {error&&<p className="auth-error" role="alert">{error}</p>}<button className="auth-submit" disabled={busy}>{busy?(signup?'Creating account…':'Signing in…'):(signup?'Create account':'Sign in')}</button>
 </form><p className="auth-switch">{signup?'Already have an account?':'New to CardLens?'} <button onClick={()=>{setError('');setScreen(signup?'login':'signup')}}>{signup?'Sign in':'Create an account'}</button></p><p className="auth-disclaimer">No bank credentials or card numbers required. Recommendations are estimates; catalog terms may be illustrative.</p></section><aside className="auth-aside"><div className="auth-orbit">C</div><span>CLARITY FOR EVERYDAY CHOICES</span><h2>Your spending,<br/>understood.</h2><p>Compare transparent estimates, explore what-if scenarios, and ask questions in your preferred way.</p></aside></main>;
}

